version: '3'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - redis
    environment:
      - DJANGO_SETTINGS_MODULE=RepBenchWeb.settings
    restart: always

  celery:
    build: .
#    shm_size: 4294967296
#    deploy:
#      resources:
#        limits:
##          cpus: "10"
#          memory: "10G"
    command: celery -A RepBenchWeb worker --loglevel=info -c 4 --concurrency=6
    volumes:
      - .:/code
    depends_on:
      - web
      - redis
    environment:
      - DJANGO_SETTINGS_MODULE=RepBenchWeb.settings
    restart: always
#    network_mode: "host"

  redis:
    image: redis
    restart: always
